server.error.include-message=always
server.error.include-binding-errors=always
server.port=8082
workforce.cors.allowed-origins=http://localhost:3000,http://localhost:3001
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
workforce.minimum-wage-api.url=
workforce.external-api.connect-timeout-ms=1000
workforce.external-api.read-timeout-ms=2000

spring.datasource.url=jdbc:postgresql://localhost:5433/workforce
spring.datasource.username=workforce
spring.datasource.password=workforce
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2s
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s
