server.error.include-message=always
server.error.include-binding-errors=always
server.port=8082
workforce.cors.allowed-origins=http://localhost:3000,http://localhost:3001

spring.datasource.url=jdbc:postgresql://localhost:5433/workforce
spring.datasource.username=workforce
spring.datasource.password=workforce
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2s
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s
